TVDM/urls.py
from django.urls import path
from .import views
from .views import userform

urlpatterns = [
    path('',views.index,name="index"),
    path('route/',userform,name="route"),
    

   
]

officer/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('fine_add/', views.fine_create_view, name='fine_add'),
    # path('fine_add/', views.finelist, name='fine_add'),
    path('fine_change/<int:pk>/', views.fine_update_view, name='fine_change'),
    path('ajax/load_locations/', views.load_locations, name='ajax_load_locations'), # AJAX
    path('offence_details/', views.offenceDetails, name='offence_details'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('driver_info/', views.driver_info, name='driver_info'),
    path('accident/', views.accident, name='accident'),
                                                          
    
    
]

vulcan/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    #path('TVDM',include('TVDM.urls')),
    path('authenticate/',include('authenticate.urls')),
    path('officer/',include('officer.urls')),
    path('driver/',include('driver.urls')),
    path('',include('TVDM.urls')),
    path('admin/', admin.site.urls),
]

officer/models.py
from pickle import TRUE
from sqlite3 import Date
from unicodedata import name
from xml.parsers.expat import model
from django.db import models
from sqlalchemy import null
#from sqlalchemy import true
from authenticate.models import Driver,User
from datetime import date,time
import datetime
import os
 
# Create your models here.
class District(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Location(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Offence(models.Model):
    offence = models.CharField(max_length=40)
    amount = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.offence
    
#class DriverName(models.Model):
    #user = models.ForeignKey(Driver, on_delete=models.CASCADE, primary_key = True)
    
    def __int__(self):
        return self.user     

class Fine(models.Model):
    id=models.AutoField(primary_key=True)
    driver = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True,null=True,limit_choices_to={'is_driver':True})
    vehicle_No = models.CharField(max_length=50)
    driver_license_No = models.CharField(max_length=124)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, blank=True, null=True)
    Nature_of_Offence = models.ForeignKey(Offence, on_delete=models.SET_NULL, blank=True, null=True)
    date = models.DateField(default=date.today)
    time = models.TimeField(default=datetime.datetime.now()) 
    Police_station = models.CharField(max_length=130)
    Issuing_officer_Name= models.CharField(max_length=20)

    def __str__(self):
        return self.id

#report accident
def filepath(request,filename):
    old_filename = filename
    timeNow = datetime.datetime.now()
    filename = "%s%s" , (old_filename,timeNow)
    return os.path.join('uploads/',filename)

class Accident(models.Model):
    id=models.AutoField(primary_key=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, blank=True, null=True)
    date = models.DateField(default=date.today)
    time = models.TimeField(default=datetime.datetime.now())
    images_of_accident = models.ImageField(default="image.png", null=True , blank=True) 
    Reporter_name = models.CharField(max_length=20)
   

officer/forms.py
from django import forms

from officer.models import Fine, Location,Accident


class FineCreationForm(forms.ModelForm):
    class Meta:
        model = Fine
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['location'].queryset = Location.objects.all()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['location'].queryset = Location.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input ; ignore and fallback to empty queryset
        elif self.instance.pk:
            self.fields['location'].queryset = self.instance.district.location_set.order_by('name')
     


class AccidentForm(forms.ModelForm):
    class Meta:
        model = Accident
        fields = '__all__'

officer/views.py
#from attr import fields
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages
from .forms import FineCreationForm,AccidentForm
from .models import Fine, Location
import logging
from .filters import Fine_filter




def fine_create_view(request):  
    form = FineCreationForm()

    if request.method == 'POST':
        form = FineCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"successful make new fine")
            return redirect('fine_add')
             
        else:
            messages.warning(request,"Invalid Data Enter")
    #console log
    #logger = logging.getLogger()
    #logger.propogate = True
    #logger.error(form)
    return render(request, 'officer/officer_index.htm', {'form': form})



def fine_update_view(request, pk):
    fine = get_object_or_404(Fine, pk=pk)
    form = FineCreationForm(instance=fine)
    if request.method == 'POST':
        form = FineCreationForm(request.POST, instance=fine)
        if form.is_valid():
            form.save()
            return redirect('fine_change', pk=pk)
              
    return render(request, 'officer/officer_index.htm', {'form': form})


# AJAX
def load_locations(request):
    district_id = request.GET.get('district_id')
    locations = Location.objects.filter(district_id=district_id).all()
    return render(request, 'officer/lcoation_list_options.htm', {'locations': locations})
    #return JsonResponse(list(cities.values('id', 'name')), safe=False)
    
def dashboard(request):
     return render(request, 'officer/dashboard.htm')

    

def offenceDetails(request):
     fines = Fine.objects.all()
     return render(request, 'officer/offence_details.htm',{'fines': fines})

#driver_infor(multyple valdue parameter)
def driver_info(request):
    finesd = Fine.objects.all()
    inforFilter = Fine_filter(request.GET, queryset=finesd)
    finesd = inforFilter.qs
    return render(request, 'officer/driver_infor.htm',{'inforFilter':inforFilter,'finesd':finesd})

#Report accident
def accident(request):
    form = AccidentForm()

    if request.method == 'POST':
        form = AccidentForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request,"successful Report accident")
            return redirect('accident')
             
        else:
            messages.warning(request,"Invalid Data Enter")
    #console log
    #logger = logging.getLogger()
    #logger.propogate = True
    #logger.error(form)
    return render(request, 'officer/accident.htm', {'form': form})
        

officer/templates/officer/accident.htm
{% extends 'authenticate/base_sub.htm' %} {% load crispy_forms_tags %}{% load static %} {% block content %} {% load widget_tweaks %}
<div class="container">
    <br>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-header text-black">
                            <h2 style="color: red;" id="fine_h">Report accident!</h2>
                            <p>Plese complete the form below for your Reporting</p>
                        </div>
                        <div class="card-body">
                            <form method="post" id="personForm" enctype="multipart/form-data" data-locations-url="{% url 'ajax_load_locations' %}" novalidate>
                                {% csrf_token %} {% for field in form.visible_fields %}
                                <div class="form-group">
                                    {{ field.label_tag }} {% render_field field class="form-control" %}{% for error in field.errors %}
                                    <span style="color:red">{{ error }}</span> {% endfor %} {% endfor %}
                                    <br>
                                    <input id="fine_btn" type="submit" value="Report" class="btn btn-block btn-danger">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>

</section>
</div>
<br> {% endblock %}

officer/templates/officer/admin.htm
{% extends 'authenticate/base_sub.htm' %} {% load crispy_forms_tags %}{% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'driver/css/style.css' %}">
<br>



<!--card-->
<div class="row">
    <div class="col-4">
        <div id="link_card" class="card">
            <div class="row">
                <center>
                    <div class="col-3">
                        <a id="card-a" href="{% url 'offence_details' %}"><i id="link_logo" class="fa fa-info-circle"></i></a>
                    </div>
                    <div class="col-9">
                        <br>
                        <a id="card-a" href="{% url 'officer_register' %}">
                            <h5 id="link_h">Offence details</h5>
                        </a>
                    </div>
                </center>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div id="link_card" class="card">
            <div class="row">
                <center>
                    <div class="col-3">
                        <a id="card-a" href="{% url 'dashboard' %}"><i id="link_logo" class="fa fa-tachometer"></i></a>
                    </div>
                    <div class="col-9">
                        <br>
                        <a id="card-a" href="{% url 'officer_register' %}">
                            <h5 id="link_h">Dashboard</h5>
                        </a>
                    </div>
                </center>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div id="link_card" class="card">
            <div class="row">
                <center>
                    <div class="col-3">
                        <a id="card-a" href="{% url 'officer_register' %}"><i id="link_logo" class="fa fa-registered"></i></a>
                    </div>
                    <div class="col-9">
                        <br>
                        <a id="card-a" href="{% url 'officer_register' %}">
                            <h5 id="link_h">Registration new officer</h5>
                        </a>
                    </div>
                </center>
            </div>
        </div>
    </div>


</div>
<br>
<br>
<br> {% endblock %}

officer/templates/officer/dashboard.htm
{% extends 'authenticate/base_sub.htm' %} {% load static %} {% load crispy_forms_tags %} {% block content %}
<link rel="stylesheet" href="{% static 'officer/css/style.css' %}">

<!--highhart link-->
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<br>
<div class="container-fluid">
    <!--dashboard header-->
    <div class="row">

        <div class="card card-header ">
            <h3 id="dm_header">Traffic Rule Violation Analysis Dashboard</h3>


        </div>

    </div>

    <br>
    <!--section 1-->
    <!--total-->
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card text-center text-black  mb-3" id="total-orders">
                    <div class="card-header">
                        <h5 class="card-title">Total fine this year</h5>
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">1500</h3>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card text-center text-black  mb-3" id="total-orders">
                    <div class="card-header">
                        <h5 class="card-title">Total fine Today</h5>
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">15</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <!--section 2-->
    <div class="row">
        <div class="col-6">
            <div class="card text-center text-black  mb-3" id="total-orders">
                <div class="card-body">
                    <figure class="highcharts-figure">
                        <div id="container"></div>
                    </figure>

                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card text-center text-black  mb-3" id="total-orders">
                <div class="card-body">
                    <figure class="highcharts-figure">
                        <div id="container1"></div>
                    </figure>
                </div>
            </div>
        </div>
    </div>

    <!--section 3-->
    <!--Map-->
    <div class="row">
        <!--iframe width="1024" height="612" src="https://app.powerbi.com/reportEmbed?reportId=2f4e9465-8626-4e8f-bd54-ee73d93692ea&autoAuth=true&ctid=49211f0f-e082-499f-94fb-96dff1601a14&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWVhc3QtYXNpYS1hLXByaW1hcnktcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQvIn0%3D" frameborder="0" allowFullScreen="true"></iframe><br/><br/-->
        <iframe title="test_vulcan - Page 1" width="1140" height="800" src="https://app.powerbi.com/reportEmbed?reportId=2f4e9465-8626-4e8f-bd54-ee73d93692ea&autoAuth=true&ctid=49211f0f-e082-499f-94fb-96dff1601a14&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWVhc3QtYXNpYS1hLXByaW1hcnktcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQvIn0%3D"
            frameborder="0" allowFullScreen="true"></iframe>
    </div>

</div>
<script>
    //barchart
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Monthly total fine in 2022'
        },
        /*subtitle: {
            text: 'Source: <a href="http://en.wikipedia.org/wiki/List_of_cities_proper_by_population">Wikipedia</a>'
        },*/
        xAxis: {
            type: 'category',
            labels: {
                rotation: -45,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Number of fine'
            }
        },
        legend: {
            enabled: false
        },
        tooltip: {
            pointFormat: 'fine : <b>{point.y:.1f} </b>'
        },
        series: [{
            name: 'Population',
            data: [
                ['January', 242],
                ['February', 208],
                ['March', 149],
                ['April', 137],
                ['May', 131],
                ['June', 127],
                ['July', 124],
                ['August', 122],
                ['September', 120],
                ['October', 117],
                ['November', 115],
                ['December', 112],
            ],
            dataLabels: {
                enabled: true,
                rotation: -90,
                color: '#FFFFFF',
                align: 'right',
                format: '{point.y}', // one decimal
                y: 10, // 10 pixels down from the top
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        }]
    });

    //pie chart
    // Radialize the colors
    Highcharts.setOptions({
        colors: Highcharts.map(Highcharts.getOptions().colors, function(color) {
            return {
                radialGradient: {
                    cx: 0.5,
                    cy: 0.3,
                    r: 0.7
                },
                stops: [
                    [0, color],
                    [1, Highcharts.color(color).brighten(-0.3).get('rgb')] // darken
                ]
            };
        })
    });

    // Build the chart
    Highcharts.chart('container1', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: 'Fien categery according to nature of fine , 2022'
        },
        /*tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },*/
        accessibility: {
            point: {
                valueSuffix: '%'
            }
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    connectorColor: 'silver'
                }
            }
        },
        series: [{
            name: 'fine',
            data: [{
                name: 'offence1',
                y: 614
            }, {
                name: 'offence2',
                y: 1184
            }, {
                name: 'offence3',
                y: 1085
            }, {
                name: 'offence4',
                y: 467
            }, {
                name: 'offence6',
                y: 418
            }, {
                name: 'offence7',
                y: 705
            }]
        }]
    });
</script>


{% endblock %}

officer/templates/officer/driver_infor.htm
{% extends 'authenticate/base_sub.htm' %} {% load crispy_forms_tags %}{% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'driver/css/style.css' %}">
<br>
<div class="container-fluid">
    <!--user filter-->
    <div class="row">
        <div class="col">
            <div class="card card-body">

                <form method="get">
                    {{inforFilter.form}}
                    <button id="logout-btn" class="btn btn-primary" type="submit">Search</button>
                </form>

            </div>
        </div>

    </div>
    <br>

    <table class="table table-light table-striped table-bordered ">

        <thead>
            <tr>
                <th scope="col">Fine id</th>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Police station</th>
                <th scope="col">Nature of offence</th>
                <th scope="col">Driving_license_No</th>
                <th scope="col">Location</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        {% for fined in finesd %}
        <tbody>
            <tr>
                <th scope="row">{{fined.id}}</th>
                <td>{{fined.date}}</td>
                <td>{{fined.time}}</td>
                <td>{{fined.Police_station}}</td>
                <td>{{fined.Nature_of_Offence}}</td>
                <td>{{fined.driver_license_No}}</td>
                <td>{{fined.location}}</td>
                <td>Pending</td>
        </tbody>
        {% endfor %}
    </table>
</div>
{% endblock %}

officer/templates/officer/location_list_option.htm
<option value="">---------</option>
{% for location in locations %}
<option value="{{ location.pk }}">{{ location.name }}</option>
{% endfor %}

officer/templates/officer/offence_details.htm
{% extends 'authenticate/base_sub.htm' %} {% load static %} {% load crispy_forms_tags %} {% block content %}
<br>
<div class="container-fluid">
    <!--offence tabel-->
    <h5>Fine list</h5>
    <div class="row">
        <div class="card card-body">

            <table class="table table-light table-striped table-bordered ">

                <thead>
                    <tr>
                        <th scope="col">Fine id</th>
                        <th scope="col">Date</th>
                        <th scope="col">Time</th>
                        <th scope="col">Police station</th>
                        <th scope="col">Nature of offence</th>
                        <th scope="col">District</th>
                        <th scope="col">Location</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                {% for fined in fines %}
                <tbody>
                    <tr>
                        <th scope="row">{{fined.id}}</th>
                        <td>{{fined.date}}</td>
                        <td>{{fined.time}}</td>
                        <td>{{fined.Police_station}}</td>
                        <td>{{fined.Nature_of_Offence}}</td>
                        <td>{{fined.district}}</td>
                        <td>{{fined.location}}</td>
                        <td>Pending</td>
                </tbody>
                {% endfor %}
            </table>

        </div>
    </div>

</div>

{% endblock %}

officer/templates/officer/officer_index.htm
{% extends 'authenticate/base_sub.htm' %}{% load widget_tweaks %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'officer/css/style.css' %}"> {% load widget_tweaks %}
<br>

<section>
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header text-black">
                        <h2 id="fine_h">DIGITAL FINE PAPER</h2>
                    </div>
                    <div class="card-body">
                        <form method="post" id="personForm" novalidate>
                            {% csrf_token %} {% for field in form.visible_fields %}
                            <div class="form-group">
                                {{ field.label_tag }} {% render_field field class="form-control" %}{% for error in field.errors %}
                                <span style="color:red">{{ error }}</span> {% endfor %} {% endfor %}
                                <br>
                                <input id="fine_btn" type="submit" value="MAKE FINE" class="btn btn-block btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>



<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function() {
        const url = $("#personForm").attr("data-locations-url"); // get the url of the `load_locations` view
        const districtId = $(this).val(); // get the selected district ID from the HTML input

        $.ajax({ // initialize an AJAX request
            url: url, // set the url of the request (= /persons/ajax/load-location/ )
            data: {
                'district_id': districtId // add the district id to the GET parameters
            },
            success: function(data) { // `data` is the return of the `load_district` view function
                $("#id_location").htm(data); // replace the contents of the city input with the data that came from the server

            }
        });

    });
</script>

<!--script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"></script-->
<br>
<br>
<br> {% endblock content %}